services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caksa-web
    restart: always
    ports:
      - "127.0.0.1:4321:8080"
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - caksa-network

networks:
  caksa-network:
    driver: bridge
