import { useEffect, useState } from "react";
import PageHero from "../components/sections/PageHero";
import { images } from "../data/images";
import { Eyebrow } from "../components/ui/editorial";

export default function About() {
  const [activeTeam, setActiveTeam] = useState("TECHNICAL");
  const [selectedDivisionName, setSelectedDivisionName] = useState<string | null>(null);
  const [selectedLeadership, setSelectedLeadership] = useState<"LEADER" | "ADVISOR" | null>(null);
  const [pastArchiveOpen, setPastArchiveOpen] = useState(false);
  const [archiveGeneration, setArchiveGeneration] = useState("GEN 04");
  const portraits = [
    "https://images.unsplash.com/photo-1587038787166-becd08a156f7?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1672457668822-a5023d2ede43?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1551239883-0d74affcc8ba?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1690166444594-e88da42a3791?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1600770320021-fda891259970?auto=format&fit=crop&w=640&q=80",
    "https://images.unsplash.com/photo-1624237489159-9dc263f9cc86?auto=format&fit=crop&w=640&q=80",
  ];
  const pastArchive = {
    "GEN 01": [["ALUMNI 01", "Applied Electronics Engineering", portraits[5]], ["ALUMNI 02", "Mechanical Engineering", portraits[1]], ["ALUMNI 03", "Informatics Engineering", portraits[2]]],
    "GEN 02": [["ALUMNI 04", "Applied Electronics Engineering", portraits[0]], ["ALUMNI 05", "Telecommunications Engineering", portraits[4]], ["ALUMNI 06", "Mechanical Engineering", portraits[5]]],
    "GEN 03": [["ALUMNI 07", "Informatics Engineering", portraits[3]], ["ALUMNI 08", "Business Management", portraits[1]], ["ALUMNI 09", "Applied Electronics Engineering", portraits[2]]],
    "GEN 04": [["ALUMNI 10", "Mechanical Engineering", portraits[4]], ["ALUMNI 11", "Creative Media Engineering", portraits[0]], ["ALUMNI 12", "Informatics Engineering", portraits[5]]],
  } as const;
  const rosters = {
    TECHNICAL: [
      ["01", "ELECTRICAL", "Power, sensors & control", [["MEMBER 01", "Applied Electronics Engineering", portraits[0]], ["MEMBER 02", "Applied Electronics Engineering", portraits[1]]]],
      ["02", "PROGRAMMING", "Autonomy & flight logic", [["MEMBER 03", "Informatics Engineering", portraits[2]], ["MEMBER 04", "Informatics Engineering", portraits[3]]]],
      ["03", "PROJECT MANAGEMENT", "Mission coordination", [["MEMBER 05", "Telecommunications Engineering", portraits[4]], ["MEMBER 06", "Business Management", portraits[5]]]],
      ["04", "MECHANICAL", "Airframe & propulsion", [["MEMBER 07", "Mechanical Engineering", portraits[1]], ["MEMBER 08", "Mechanical Engineering", portraits[0]]]],
    ],
    "NON-TECHNICAL": [
      ["01", "ADMINISTRATION", "Operations & documentation", [["MEMBER 09", "Business Management", portraits[3]], ["MEMBER 10", "Applied Business Administration", portraits[2]]]],
      ["02", "BRANDING", "Visual identity & content", [["MEMBER 11", "Creative Media Engineering", portraits[5]], ["MEMBER 12", "Digital Media", portraits[0]]]],
      ["03", "PUBLIC RELATIONS", "Community & communications", [["MEMBER 13", "Communication Studies", portraits[4]], ["MEMBER 14", "Digital Media", portraits[3]]]],
      ["04", "PROJECT MANAGEMENT", "Partnership & logistics", [["MEMBER 15", "Business Management", portraits[1]], ["MEMBER 16", "Applied Business Administration", portraits[2]]]],
    ],
  } as const;
  const currentRoster = rosters[activeTeam as keyof typeof rosters];
  const selectedDivision = currentRoster.find(([, division]) => division === selectedDivisionName);
  const leadershipProfile = selectedLeadership === "LEADER"
    ? ["TEAM LEADER", "FLIGHT LEAD", "LEADER 01", "Applied Electronics Engineering", portraits[0]] as const
    : selectedLeadership === "ADVISOR"
      ? ["ADVISOR", "ACADEMIC GUIDE", "ADVISOR 01", "Applied Electronics Engineering", portraits[4]] as const
      : null;
  useEffect(() => {
    if (!selectedDivision && !selectedLeadership && !pastArchiveOpen) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = previousOverflow; };
  }, [selectedDivision, selectedLeadership, pastArchiveOpen]);
  return <PageHero label="About CAKSA" title={<>GALA AKASA<br /><em>WIRYA SATYA.</em></>} description="A wish to rise through the sky with courage, strength, and purpose." image={images.team}>
    <section className="about-manifesto section-light"><div className="about-yearline"><span>2007</span><i /><span>2022</span><i /><span>NOW</span></div><div className="about-manifesto-copy"><Eyebrow>Why we exist</Eyebrow><h2>WE TURN<br />CURIOSITY INTO<br /><em>FLIGHT.</em></h2><p>CAKSA grew from the Aeronautics PENS legacy into an international UAV research team. We work where engineering discipline meets a shared belief: Indonesian ideas deserve room in the global sky.</p></div><aside className="about-quote">“THE HORIZON IS NOT<br />A LIMIT. IT IS A<br />DIRECTION.”</aside></section>
    <section className="vision-mission section-dark"><div className="vision-card"><span>[ 01 ] / VISION</span><h2>TO BE A<br /><em>RECOGNISED</em><br />UAV RESEARCH<br />FORCE.</h2><p>We aim to carry student-built aerial research from Surabaya into meaningful international exchange.</p></div><div className="mission-card-about"><span>[ 02 ] / MISSION</span><ol><li>Advance practical UAV research through rigorous experimentation.</li><li>Build a multidisciplinary learning environment for every member.</li><li>Represent Indonesia with credible work on international stages.</li></ol></div></section>
    <section className="leadership section-light"><div className="leadership-heading"><Eyebrow>People who hold the line</Eyebrow><h2>LEADERSHIP<br />IN <em>FORMATION.</em></h2></div><div className="leadership-grid"><article role="button" tabIndex={0} onClick={() => setSelectedLeadership("LEADER")} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedLeadership("LEADER"); } }}><span>01 / TEAM LEADER</span><h3>FLIGHT<br />LEAD</h3><p>Guides the team’s technical direction, mission decisions, and working rhythm.</p><b>OPEN PROFILE ↗</b></article><article role="button" tabIndex={0} onClick={() => setSelectedLeadership("ADVISOR")} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedLeadership("ADVISOR"); } }}><span>02 / ADVISOR</span><h3>ACADEMIC<br />GUIDE</h3><p>Connects research ambition with academic rigor and institutional perspective.</p><b>OPEN PROFILE ↗</b></article></div><p className="roster-note">SELECT A LEADERSHIP ROLE TO OPEN ITS PROFILE INDEX / PLACEHOLDER DATA IS READY FOR THE OFFICIAL ROSTER.</p>{leadershipProfile && <div className="member-index leadership-index" role="dialog" aria-modal="true" aria-label={`${leadershipProfile[0]} profile`}><div className="member-index-top"><span>CAKSA / LEADERSHIP INDEX</span><span>0{selectedLeadership === "LEADER" ? "1" : "2"} / PROFILE</span><button type="button" onClick={() => setSelectedLeadership(null)}><i /><i /> CLOSE</button></div><div className="member-index-heading"><span>ROLE / {leadershipProfile[0]}</span><h2>{leadershipProfile[1]}</h2><p>{leadershipProfile[0] === "TEAM LEADER" ? "Technical direction, mission calls, and team momentum." : "Academic perspective, research rigor, and strategic guidance."}</p></div><div className="member-stage leadership-stage"><article className="member-stage-card"><div className="member-stage-photo"><img src={leadershipProfile[4]} alt={`Placeholder portrait for ${leadershipProfile[2]}`} /><span>PROFILE / LEADERSHIP</span></div><div className="member-stage-copy"><h3>{leadershipProfile[2]}</h3><p>{leadershipProfile[3]}</p><small>PLACEHOLDER PROFILE / CAKSA ROSTER</small></div></article></div><div className="member-index-foot"><span>GALA AKASA WIRYA SATYA</span><button type="button" onClick={() => setSelectedLeadership(null)}>RETURN TO LEADERSHIP ↙</button></div></div>}</section>
    <section className="team-atlas section-dark"><div className="atlas-top"><div><Eyebrow>Team atlas / current roster</Eyebrow><h2>TWO WINGS.<br /><em>ONE</em> FLIGHT.</h2></div><p>CAKSA brings technical craft and organizational care into one formation. Select a wing to explore its working divisions.</p></div><div className="atlas-tabs" role="tablist"><button type="button" role="tab" aria-selected={activeTeam === "TECHNICAL"} className={activeTeam === "TECHNICAL" ? "active" : ""} onClick={() => { setActiveTeam("TECHNICAL"); setSelectedDivisionName(null); }}>01 / TECHNICAL <b>↘</b></button><button type="button" role="tab" aria-selected={activeTeam === "NON-TECHNICAL"} className={activeTeam === "NON-TECHNICAL" ? "active" : ""} onClick={() => { setActiveTeam("NON-TECHNICAL"); setSelectedDivisionName(null); }}>02 / NON-TECHNICAL <b>↘</b></button></div><div className="division-roster">{currentRoster.map(([number, division, focus, members]) => <article key={division} role="button" tabIndex={0} onClick={() => setSelectedDivisionName(division)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedDivisionName(division); } }}><div className="division-index">{number}</div><div><h3>{division}</h3><p>{focus}</p></div><div className="roster-preview"><span>OPEN MEMBER INDEX</span><b>↗</b></div></article>)}</div><p className="atlas-footnote">SELECT A DIVISION TO OPEN ITS MEMBER INDEX. PROFILE DATA IS A PLACEHOLDER AND READY TO BE REPLACED WITH THE OFFICIAL ROSTER.</p>{selectedDivision && <div className="member-index" role="dialog" aria-modal="true" aria-label={`${selectedDivision[1]} member index`}><div className="member-index-top"><span>CAKSA / {activeTeam} WING</span><span>{selectedDivision[0]} / MEMBER INDEX</span><button type="button" onClick={() => setSelectedDivisionName(null)}><i /><i /> CLOSE</button></div><div className="member-index-heading"><span>DIVISION / {selectedDivision[0]}</span><h2>{selectedDivision[1]}</h2><p>{selectedDivision[2]}</p></div><div className="member-stage">{selectedDivision[3].map(([name, major, photo], index) => <article key={name} className={`member-stage-card stage-${index + 1}`}><div className="member-stage-photo"><img src={photo} alt={`Placeholder portrait for ${name}`} /><span>PROFILE / 0{index + 1}</span></div><div className="member-stage-copy"><h3>{name}</h3><p>{major}</p><small>PLACEHOLDER PROFILE / CAKSA ROSTER</small></div></article>)}</div><div className="member-index-foot"><span>GALA AKASA WIRYA SATYA</span><button type="button" onClick={() => setSelectedDivisionName(null)}>RETURN TO TEAM ATLAS ↙</button></div></div>}</section>
    <section className="past-members"><div><Eyebrow>Legacy archive</Eyebrow><h2>FOUR<br />GENERATIONS<br />OF <em>FLIGHT.</em></h2><p>From Aeronautics PENS to CAKSA, every generation left a method, a sketch, a solution, or an unanswered question for the next crew.</p></div><div className="past-detail-entry"><span>2007—NOW / PEOPLE ARCHIVE</span><strong>PAST<br />MEMBERS</strong><p>A searchable record for four generations of alumni. Open the archive to view each generation’s placeholder roster.</p><button type="button" onClick={() => setPastArchiveOpen(true)}>OPEN GENERATION INDEX <b>↗</b></button></div><div className="past-data"><span>ALUMNI ARCHIVE</span><p>Official names, majors, and portraits can replace this placeholder archive whenever the roster is ready.</p></div>{pastArchiveOpen && <div className="past-index" role="dialog" aria-modal="true" aria-label="Past member generation archive"><div className="past-index-top"><span>CAKSA / LEGACY ARCHIVE</span><span>2007—NOW / 04 GENERATIONS</span><button type="button" onClick={() => setPastArchiveOpen(false)}><i /><i /> CLOSE</button></div><div className="past-index-heading"><span>PEOPLE WHO BUILT THE RUNWAY</span><h2>PAST<br /><em>MEMBERS.</em></h2></div><div className="generation-tabs">{Object.keys(pastArchive).map((generation) => <button key={generation} type="button" className={archiveGeneration === generation ? "active" : ""} onClick={() => setArchiveGeneration(generation)}>{generation}</button>)}</div><div className="generation-roster">{pastArchive[archiveGeneration as keyof typeof pastArchive].map(([name, major, photo], index) => <article key={name}><div><img src={photo} alt={`Placeholder portrait for ${name}`} /><span>ALUMNI / 0{index + 1}</span></div><h3>{name}</h3><p>{major}</p></article>)}</div><div className="past-index-foot"><span>PLACEHOLDER ARCHIVE / READY FOR OFFICIAL ROSTER</span><button type="button" onClick={() => setPastArchiveOpen(false)}>RETURN TO ABOUT ↙</button></div></div>}</section>
  </PageHero>;
}
